#pragma once
#if defined(SUPPORT_WAB_NPDISP) && defined(SUPPORT_NPDISP_D3D)
typedef struct { UINT8* pixels; UINT32 width,height; SINT32 pitch; UINT32 bpp; } NPDISP_D3D_SW_TARGET;
typedef struct { UINT8* pixels; UINT32 width,height; SINT32 pitch; } NPDISP_D3D_SW_DEPTH_TARGET;
bool npdisp_d3d_sw_clear(NPDISP_D3D_SW_TARGET*, SINT32,SINT32,SINT32,SINT32,UINT32);
bool npdisp_d3d_sw_clearDepthStencil(NPDISP_D3D_SW_DEPTH_TARGET*, SINT32,SINT32,SINT32,SINT32,UINT16,UINT32,UINT32,UINT32,UINT32);
bool npdisp_d3d_sw_point(NPDISP_D3D_SW_TARGET*, NPDISP_D3D_SW_DEPTH_TARGET*, const NPDISP_D3D_VERTEX*, const NPDISP_D3D_RASTERSTATE*);
bool npdisp_d3d_sw_line(NPDISP_D3D_SW_TARGET*, NPDISP_D3D_SW_DEPTH_TARGET*, const NPDISP_D3D_VERTEX*, const NPDISP_D3D_VERTEX*, const NPDISP_D3D_RASTERSTATE*);
bool npdisp_d3d_sw_triangle(NPDISP_D3D_SW_TARGET*, NPDISP_D3D_SW_DEPTH_TARGET*, const NPDISP_D3D_VERTEX*, const NPDISP_D3D_VERTEX*, const NPDISP_D3D_VERTEX*, const NPDISP_D3D_RASTERSTATE*);
#endif
